-- AlterTable
ALTER TABLE "Bids" ALTER COLUMN "amount" SET DATA TYPE BIGINT,
ALTER COLUMN "price" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Offers" ALTER COLUMN "amount" SET DATA TYPE BIGINT,
ALTER COLUMN "price" SET DATA TYPE BIGINT;
